# Generated by Django 4.0.6 on 2022-07-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('number', models.IntegerField(verbose_name='Numero_Pokedex')),
                ('clasificacion', models.TextField(verbose_name='Clasificacion')),
                ('tipo1', models.TextField(verbose_name='Tipo_1')),
                ('tipo2', models.TextField(verbose_name='Tipo_2')),
                ('peso', models.TextField(verbose_name='Peso')),
                ('altura', models.IntegerField(verbose_name='Altura')),
                ('propm', models.FloatField(verbose_name='Probabilidad_Macho')),
                ('proph', models.FloatField(verbose_name='Probabilidad_Hembra')),
                ('habilidades', models.TextField(verbose_name='Habilidades')),
                ('ps', models.IntegerField(verbose_name='PS')),
                ('ataque', models.IntegerField(verbose_name='Ataque')),
                ('defensa', models.IntegerField(verbose_name='Defensa')),
                ('sp_ataque', models.IntegerField(verbose_name='Ataque_Especial')),
                ('sp_defensa', models.IntegerField(verbose_name='Defensa_Especial')),
                ('speed', models.IntegerField(verbose_name='Velocidad')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('bicho', models.FloatField(verbose_name='Contra_Bicho')),
                ('siniestro', models.FloatField(verbose_name='Contra_Siniestro')),
                ('dragon', models.FloatField(verbose_name='Contra_Dragon')),
                ('electrico', models.FloatField(verbose_name='Contra_Electrico')),
                ('hada', models.FloatField(verbose_name='Contra_Hada')),
                ('lucha', models.FloatField(verbose_name='Contra_Lucha')),
                ('fuego', models.FloatField(verbose_name='Contra_Fuego')),
                ('volador', models.FloatField(verbose_name='Contra_Volador')),
                ('fantasma', models.FloatField(verbose_name='Contra_Fantasma')),
                ('planta', models.FloatField(verbose_name='Contra_Planta')),
                ('tierra', models.FloatField(verbose_name='Contra_Tierra')),
                ('hielo', models.FloatField(verbose_name='Contra_Hielo')),
                ('normal', models.FloatField(verbose_name='Contra_Normal')),
                ('veneno', models.FloatField(verbose_name='Contra_Veneno')),
                ('psiquico', models.FloatField(verbose_name='Contra_Psiquico')),
                ('roca', models.FloatField(verbose_name='Contra_Roca')),
                ('acero', models.FloatField(verbose_name='Contra_Acero')),
                ('agua', models.FloatField(verbose_name='Contra_Agua')),
                ('legendario', models.IntegerField(verbose_name='Legendario')),
                ('generacion', models.IntegerField(verbose_name='Generacion')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='alto_mando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pokemon', models.CharField(max_length=30)),
                ('best_pokemon', models.CharField(max_length=30)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neodex.trainer')),
            ],
        ),
    ]
