from django.db import models
import csv

# Create your models here.

class pokemon(models.Model):
    Nombre=models.TextField(("Nombre"))
    Numero_Pokedex=models.IntegerField(("Numero_Pokedex"))
    Clasificacion=models.TextField(("Clasificacion"))
    Tipo_1=models.TextField(("Tipo_1"))
    Tipo_2=models.TextField(("Tipo_2"))
    Peso=models.TextField(("Peso"))
    Altura=models.IntegerField(("Altura"))
    Probabilidad_Macho=models.FloatField(("Probabilidad_Macho"))
    Probabilidad_Hembra=models.FloatField(("Probabilidad_Hembra"))
    Habilidades=models.TextField(("Habilidades"))
    PS=models.IntegerField(("PS"))
    Ataque=models.IntegerField(("Ataque"))
    Defensa=models.IntegerField(("Defensa"))
    Ataque_Especial=models.IntegerField(("Ataque_Especial"))
    Defensa_Especial=models.IntegerField(("Defensa_Especial"))
    Velocidad=models.IntegerField(("Velocidad"))
    Total=models.IntegerField(("Total"))
    Contra_Bicho=models.FloatField(("Contra_Bicho"))
    Contra_Siniestro=models.FloatField(("Contra_Siniestro"))
    Contra_Dragon=models.FloatField(("Contra_Dragon"))
    Contra_Electrico=models.FloatField(("Contra_Electrico"))
    Contra_Hada=models.FloatField(("Contra_Hada"))
    Contra_Lucha=models.FloatField(("Contra_Lucha"))
    Contra_Fuego=models.FloatField(("Contra_Fuego"))
    Contra_Volador=models.FloatField(("Contra_Volador"))
    Contra_Fantasma=models.FloatField(("Contra_Fantasma"))
    Contra_Planta=models.FloatField(("Contra_Planta"))
    Contra_Tierra=models.FloatField(("Contra_Tierra"))
    Contra_Hielo=models.FloatField(("Contra_Hielo"))
    Contra_Normal=models.FloatField(("Contra_Normal"))
    Contra_Veneno=models.FloatField(("Contra_Veneno"))
    Contra_Psiquico=models.FloatField(("Contra_Psiquico"))
    Contra_Roca=models.FloatField(("Contra_Roca"))
    Contra_Acero=models.FloatField(("Contra_Acero"))
    Contra_Agua=models.FloatField(("Contra_Agua"))
    Legendario=models.IntegerField(("Legendario"))
    Generacion=models.IntegerField(("Generacion"))

class Trainer(models.Model):
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    team=models.CharField(max_length=100)
    pokemon_1=models.CharField(max_length=100)
    pokemon_2=models.CharField(max_length=100)
    pokemon_3=models.CharField(max_length=100)
    pokemon_4=models.CharField(max_length=100)
    pokemon_4=models.CharField(max_length=100)
    pokemon_5=models.CharField(max_length=100)
    pokemon_6=models.CharField(max_length=100)

class alto_mando(models.Model):
    name=models.ForeignKey(Trainer, on_delete=models.CASCADE)
    type_pokemon=models.CharField(max_length=30)
    best_pokemon=models.CharField(max_length=30)